const cartItems = [
  {
    id: "rec1JZlfCIBOPdcT2",
    title: "The Great Gatsby",
    author: "F. Scott Fitzgerald",
    price: 12.99,
    quantity: 2,
    description: "A classic novel about the American Dream.",
    img: "https://source.unsplash.com/random/?Book&1",
  },
  {
    id: "recB6qcHPxb62YJ75",
    title: "To Kill a Mockingbird",
    author: "Harper Lee",
    price: 10.99,
    quantity: 1,
    description: "A powerful story of racial injustice in the South.",
    img: "https://source.unsplash.com/random/?book&4",
  },
  {
    id: "recdRxBsE14Rr2VuJ",
    title: "1984",
    author: "George Orwell",
    price: 14.99,
    quantity: 3,
    description: "A dystopian novel depicting a totalitarian regime.",
    img: "https://source.unsplash.com/random/?book&2",
  },
  {
    id: "2ecwTo160XST3PIoW",
    title: "Pride and Prejudice",
    author: "Jane Austen",
    price: 9.99,
    quantity: 2,
    description: "A classic romance novel.",
    img: "https://source.unsplash.com/random/?book&3",
  },
  // Add more book items with titles, authors, quantities, descriptions, and prices
  {
    id: "recwTo160XST3PIoW",
    title: "The Catcher in the Rye",
    author: "J.D. Salinger",
    price: 11.99,
    quantity: 1,
    description: "A coming-of-age novel.",
    img: "https://source.unsplash.com/random/?book&5",
  },
  {
    id: "re3wTo160XST3PIoW",
    title: "Harry Potter and the Sorcerer's Stone",
    author: "J.K. Rowling",
    price: 14.99,
    quantity: 4,
    description: "The first book in the Harry Potter series.",
    img: "https://source.unsplash.com/random/?book&6",
  },
  {
    id: "recdTo160XST3PIoW",
    title: "The Hobbit",
    author: "J.R.R. Tolkien",
    price: 13.99,
    quantity: 1,
    description: "A fantasy novel.",
    img: "https://source.unsplash.com/random/?book&7",
  },
  {
    id: "recwTo460XST3PIoW",
    title: "The Da Vinci Code",
    author: "Dan Brown",
    price: 12.49,
    quantity: 3,
    description: "A thriller novel.",
    img: "https://source.unsplash.com/random/?book&8",
  },
  {
    id: "recwT2160XST3PIoW",
    title: "The Alchemist",
    author: "Paulo Coelho",
    price: 10.99,
    quantity: 2,
    description: "A philosophical novel.",
    img: "https://source.unsplash.com/random/?book&9",
  },
  {
    id: "recwTo260XST3PIoW",
    title: "The Shining",
    author: "Stephen King",
    price: 13.99,
    quantity: 1,
    description: "A horror novel.",
    img: "https://source.unsplash.com/random/?book&10",
  },
  {
    id: "recwTo166XST3PIoW",
    title: "The Girl with the Dragon Tattoo",
    author: "Stieg Larsson",
    price: 12.99,
    quantity: 2,
    description: "A mystery novel.",
    img: "https://source.unsplash.com/random/?book&11",
  },
  {
    id: "recwTo160XSE3PIoW",
    title: "Brave New World",
    author: "Aldous Huxley",
    price: 11.99,
    quantity: 1,
    description: "A dystopian novel.",
    img: "https://source.unsplash.com/random/?book&12",
  },
  {
    id: "recwTo160XST6PIoW",
    title: "Lord of the Rings",
    author: "J.R.R. Tolkien",
    price: 15.99,
    quantity: 3,
    description: "A fantasy epic.",
    img: "https://source.unsplash.com/random/?book&13",
  },
  {
    id: "recwTo160XST7PIoW",
    title: "The Road",
    author: "Cormac McCarthy",
    price: 12.49,
    quantity: 2,
    description: "A post-apocalyptic novel.",
    img: "https://source.unsplash.com/random/?book&14",
  },
  {
    id: "recwTo160XST8PIoW",
    title: "The Hunger Games",
    author: "Suzanne Collins",
    price: 9.99,
    quantity: 4,
    description: "A dystopian adventure novel.",
    img: "https://source.unsplash.com/random/?book&15",
  },
];

export default cartItems;
